source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HanekeObjc_Example' do
  pod 'HanekeObjc', :path => '../'
end

target 'HanekeObjc_Tests' do
  pod 'HanekeObjc', :path => '../'

  #pod 'Quick', '~> 0.9.0'
  #pod 'Nimble', '~> 4.0.0'
end
